# syntax=docker/dockerfile:1

FROM node:20-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
RUN corepack enable && corepack prepare pnpm@9.15.9 --activate

FROM base AS deps
COPY package.json pnpm-lock.yaml* ./
RUN if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else pnpm install --no-frozen-lockfile; fi

FROM base AS builder
ARG NEXT_PUBLIC_MASTER_PANEL_URL
ARG NEXT_PUBLIC_MASTER_API_URL
ARG NEXT_PUBLIC_SITE_CODE
ARG NEXT_PUBLIC_FEED_REVALIDATE_SECONDS
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_TAGLINE
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_SITE_DOMAIN
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SITE_OG_IMAGE
ENV NEXT_PUBLIC_MASTER_PANEL_URL=$NEXT_PUBLIC_MASTER_PANEL_URL
ENV NEXT_PUBLIC_MASTER_API_URL=$NEXT_PUBLIC_MASTER_API_URL
ENV NEXT_PUBLIC_SITE_CODE=$NEXT_PUBLIC_SITE_CODE
ENV NEXT_PUBLIC_FEED_REVALIDATE_SECONDS=$NEXT_PUBLIC_FEED_REVALIDATE_SECONDS
ENV NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME
ENV NEXT_PUBLIC_SITE_TAGLINE=$NEXT_PUBLIC_SITE_TAGLINE
ENV NEXT_PUBLIC_SITE_DESCRIPTION=$NEXT_PUBLIC_SITE_DESCRIPTION
ENV NEXT_PUBLIC_SITE_DOMAIN=$NEXT_PUBLIC_SITE_DOMAIN
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_OG_IMAGE=$NEXT_PUBLIC_SITE_OG_IMAGE
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
RUN addgroup -S nodejs && adduser -S nextjs -G nodejs
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
