services:
  1fwckn4ypf:
    container_name: 1fwckn4ypf_app
    image: ghcr.io/mr-devloper005/youngerlifestyle.net:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3221:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
