export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Verified businesses and services.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Local offers, jobs, and deals.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Article',
    route: '/article',
    description: 'Insights, blogs, and long-form content.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Galleries and media-first posts.',
    contentType: 'image',
    enabled: false,
  },
  {
  key: 'profile',
  label: 'Profile',
  route: '/profile',
  description: 'Curated profile content.',
  contentType: 'profile',
  enabled: true,
},
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Curated bookmarks and resources.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Commentary and response posts.',
    contentType: 'comment',
    enabled: false,
  },
  {
  key: 'pdf',
  label: 'PDF',
  route: '/pdf',
  description: 'Curated pdf content.',
  contentType: 'pdf',
  enabled: true,
},
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Organization profiles and directories.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
